name: Build

on:
  push:
    branches: [main]
  pull_request:

env:
    NEXT_PUBLIC_KONTENT_ENVIRONMENT_ID: 2cedc519-a547-01ba-dde7-b01e00b909a1
    KONTENT_COLLECTION_CODENAME: ficto_healthtech_surgical

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

        id: nvm
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run lint
      - run: npm run build
            
